name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions
# event name
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the CI."
      - run: echo "The workflow is now ready to test code on the CI."

      # Check code list
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      # Run tests and upload coverage
      # - run: echo "The workflow is now ready to run tests and upload coverage."
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with: 
      #     python-version: "3.10"
      # - name: Install dependencies
      #   run: pip install pytest pytest-cov
      # - name: Install IDDM dependencies
      #   run: pip install -r requirements.txt
      # - name: Run tests
      #   run: pytest --cov-branch --cov-report=xml
      # - name: Upload results to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      # - run: echo "The workflow is now finish to run tests and upload coverage."

      # Auto sync gitee
      - run: echo "The workflow is now ready to sync to gitee."
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:chairc/Integrated-Design-Diffusion-Model.git
          destination-repo: git@gitee.com:chairc/Integrated-Design-Diffusion-Model.git
      - run: echo "The workflow is now finish to sync to gitee."
      - run: echo "This job's status is ${{ job.status }}."
